[2024-06-27 12:55:48,736: INFO: main: Welcom to the codebase]
[2024-07-10 09:40:39,903: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-10 09:40:39,903: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-10 10:47:54,910: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-10 10:47:54,913: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-10 10:50:07,378: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-10 10:50:07,385: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-10 12:37:48,394: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-10 12:37:48,399: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-11 06:24:56,811: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-11 06:24:56,819: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-11 06:33:08,314: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-11 06:33:08,318: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-11 07:48:39,913: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-11 07:48:39,913: INFO: common: created directory at: artifacts]
[2024-07-11 07:48:39,920: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-11 07:48:39,922: INFO: 2579417938: Downloading data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2024-07-11 07:48:59,343: INFO: 2579417938: Downloaded data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into artifacts/data_ingestion/data.zip]
[2024-07-12 21:29:29,501: INFO: main: <------Stage Data Ingestion Started------>]
[2024-07-12 21:29:29,501: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-12 21:29:29,501: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-12 21:29:29,516: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "C:\Users\HP\Cancer Detection\src\cnnClassifier\utils\common.py", line 33, in read_yaml
    return ConfigBox(content)
  File "box\\box.py", line 296, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    obj.main()
  File "C:\Users\HP\Cancer Detection\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
  File "C:\Users\HP\Cancer Detection\src\cnnClassifier\config\configuration.py", line 9, in __init__
    self.params = read_yaml(params_filepath)
  File "C:\Users\HP\anaconda3\envs\myenv\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "C:\Users\HP\Cancer Detection\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-07-12 21:30:21,551: INFO: main: <------Stage Data Ingestion Started------>]
[2024-07-12 21:30:21,551: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-12 21:30:21,551: INFO: common: created directory at: artifacts]
[2024-07-12 21:30:21,551: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-12 21:30:21,551: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2024-07-12 21:30:44,726: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into artifacts/data_ingestion/data.zip]
[2024-07-12 21:30:45,423: INFO: main: <-------Stage Data Ingestion Completed]
